### PR TITLE
Invincibility

### PR DESCRIPTION
**Pull request by Sykel**
Adding invincibility checks to all combat CRs.

I don't see any functional reason why you would want to hit something that is invulnerable.

Some thoughts:

pro-hitting while invulnerable
precasting while something is about to become vulnerable -- (potentially?) (PLD, healers, casters)
RDM proc-ing dualcast (maybe)

con-hitting while invulnerable
DoTs? -- you can't apply a DoT while something in invulnerable.
you might use a ogcd which did no damage.
you don't get gauge if you do no damage. (RDM, DNC, MCH)

### CODE REVIEW

**Comment by cheesegoldfish** [comment]
The only exception here I can see is the classes that actually do need to cast something with that downtime, even moreso for some classes.

For example. Reaper will want to recast soulsow if something is invuln, its a 5 second charge that is great to have a gcd when out of melee range, and some fights when the boss is invuln or disappears, its a great time to refresh it.

Any of the dps classes would want to cast second wind, they could have low hp, even if the boss is invuln, but they need that second wind, which normally is casted in a weaving window.

There are other classes that may need to cast various different things, so I think just a check at the start of each combat pulse is too harsh, and could be tweaked for each individual class.

**Comment by Sykel** [comment]
I'd be willing to update all buffs across all jobs to stop the CR from hitting bosses/enemies while invul (but I can break this into a per-job project if you prefer, but I think it should be clean-enough to read in a single PR, let me know your thoughts).

I can add a code-block above this check for the non-targetable case.

Uses here would include:
Tank/healer mitigations
MNK fists of wind/earth (potentially, this one is a stretch, and I don't play MNK, and you have to reapply fires once you enter combat, so eh)
NIN prepping a jutsu
RPR soulsow
Phys second wind (and dancer curing waltz) while untargeted
BRD mitigation or BRD esuna
DNC preparing a dance (but dances have a duration, so I don't think this should be implemented.) This should be manual I think.
Healers/Casters with Lucid Dreaming when under MP threshhold
RDM vercuring during transitions, this will open raises during transitions.
BLM mitigation (stretch but ehh)


unsupported cases
pld wings
sam meditation
dnc improv

Thoughts?

**Comment by cheesegoldfish** [comment]
Yeah. I think it would be nicer to do it per job... because then you can manually test each job on a per pr basis. Sweeping changes like this are kinda hard to test when you have to make sure every single job does the correct thing for a single merge.

Also we might not need all that stuff right away, it was just something I was pointing out that we will end up missing if this PR goes in, since effectively it stops all combat pulses, gambits, openers, etc.

**Comment by EssexDraven** [comment]
I want to merge this, but I suspect it will impact things like multi-dotting. Will check more deeply soon!

**Comment by wildchill** [comment]
Seems like this PR never really made it. Going to close it out, if we want to resurrect it then we can reopen it later on.

**Pull request closed without merging**
