### PR TITLE
Reaper changes. Don't waste enhanced gallows/gibbet for shadow of dea…

### PR DESCRIPTION
**Pull request by cheesegoldfish**
…th. Under level 90, use all stacks of lemure shroud. Add usage of soulsow and harvestmoon for in between pulls.

### CODE REVIEW

**Comment by cheesegoldfish** [comment]
Why was this completely rejected? Just let me know because I intend to continue contributing and would like to make sure things are up to par.

I also am wondering, when reaper is at level 84, it just stays in reapers shroud with 1 stack and does nothing, since there is no communio, the bot just stares at the enemy in a threatening manner but doesn't attack anymore until shroud times out.

Master is also missing a few other things. Currently the routine will cast shadow of death, even if it has a stack of Soul Reaver, which ends up wasting the soul reaver stack, since if you cast any weaponskill it removes the soul reaver stack.

**Comment by NotIllu** [comment]
Haven't seen this PR before I made the changes you mentioned.
So if I havent missed something, everything you mentioned is now implemented.
Thats why I closed it, should have made a comment about it in the first place, sorry.

**Comment by NotIllu** [comment]
So if its still missing stuff, doing the priority list wrong.
feel free to submit another PR and ping @NV in discord or just post that you made a PR.

**Comment by cheesegoldfish** [comment]
Thanks.

At least we put things in the same places, so I'm full glad to know I was on the right track in my thinking of how to code and match the surrounding code in this repo.

I'll be making a new PR, there are still some issues at level 84 that could be smoothed out.  Usually I code the changes while inside the dungeon so I can reload and test them live, so it will be when I am online again and running some dungeons on reaper.

**Pull request closed without merging**
